name: flutter_qiyu
description: 适用于 Flutter 的七鱼客服插件
version: 0.1.2
homepage: https://github.com/leanflutter/flutter_qiyu

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.leanflutter.plugins.flutter_qiyu
        pluginClass: FlutterQiyuPlugin
      ios:
        pluginClass: FlutterQiyuPlugin
